import type { NextPage } from "next";
import Head from "next/head";
import { NewTaskButton } from "components/Atoms/NewTaskButton";
import { Menu } from "components/Organisms/Menu";
import { Navbar } from "components/Organisms/Navbar";
import { MainContainer, Container } from "styles/home";
import { Greeting } from "components/Molecules/Greeting";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SaúdeTasks - Exames, Consultas e Cirurgias</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.saudeid.com.br/favicon-32x32.png?v=a5c8821faa0ec5cc8340bb445dc291e3"
        />
      </Head>

      <Container>
        <Menu />
        <MainContainer>
        <Navbar />
          <Greeting />
          <NewTaskButton />
        </MainContainer>
      </Container>
    </>
  );
};

export default Home;
